postgresql:
  host: localhost
  port: 5432
  user: user
  password: pass
  database: staging_process
  replica_host: null
  replica_port: null
  min_pool_size: 5
  max_pool_size: 20
sqlserver:
  host: localhost
  port: 1433
  user: user
  password: pass
  database: smart_pro_claims
  pool_size: 5
processing:
  batch_size: 1000
  max_workers: 4
  conversion_factor: 36.04
  insert_workers: 2
security:
  api_key: changeme
  encryption_key: changeme
cache:
  redis_url: null
  warm_rvu_codes: []
  predictive_ahead: 2
model:
  path: model.joblib
  version: "1"
  ab_test_path: null
  ab_test_ratio: 0.5
logging:
  level: INFO
  aggregator_host: null
  aggregator_port: null
  component_levels: {}
  rotate_mb: 10
  backup_count: 5
  sentry_dsn: null
features:
  enable_cache: true
  enable_model_monitor: true
