postgresql:
  host: localhost
  port: 5432
  user: user
  password: pass
  database: staging_process
  replica_host: null
  replica_port: null
sqlserver:
  host: localhost
  port: 1433
  user: user
  password: pass
  database: smart_pro_claims
processing:
  batch_size: 1000
  max_workers: 4
  conversion_factor: 36.04
security:
  api_key: changeme
  encryption_key: changeme
cache:
  redis_url: null
  warm_rvu_codes: []
model:
  path: model.joblib
logging:
  level: INFO
  aggregator_host: null
  aggregator_port: null
  component_levels: {}
