apiVersion: apps/v1
kind: Deployment
metadata:
  name: claims-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claims-processing
  template:
    metadata:
      labels:
        app: claims-processing
    spec:
      containers:
      - name: app
        image: claims-processing:latest
        env:
        - name: APP_ENV
          value: production
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: claims-processing
spec:
  selector:
    app: claims-processing
  ports:
  - port: 80
    targetPort: 8000
